[phases.setup]
nixPkgs = ["nodejs_20", "python3", "pkg-config", "postgresql", "pnpm"]

[phases.build]
cmds = [
  "pnpm install --frozen-lockfile",
  "npx prisma generate --schema ./prisma/pgsql/schema.prisma",
  "pnpm run build"
]

[start]
cmd = "node server.js"

[variables]
NODE_ENV = "production"
NEXT_TELEMETRY_DISABLED = "1"
DB_TYPE = "pgsql"
